### ISSUE TITLE
Can't enable SSL in UVM WebDB with Matomo

### ISSUE THREAD

**Issue by YYinBurgh** [YYinBurgh/DAITA_matomo#1]
When turning on SSL on UVM WebDB, Matomo shows "An Error Occured/Database access denied", so we can't enable SSL in UVM WebDB with Matomo.

**Comment by simba-source** [comment]
I have successfully added the SSL Certificate to the database manually. Despite the error that occurs when enabling the SSL button on the WebDB website, the database connection is still secure. You can find the solution to this issue in the [Secure Database Connection with SSL](https://github.com/YYinBurgh/DAITA_matomo/#two-ways-to-secure-database-connection-with-ssl) section of the README.
